import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, BookOpen, LayoutGrid, GraduationCap, Settings, LogOut, Search, Plus, X, Users, ChevronRight, Sparkles, Library, Check, LoaderCircle } from 'lucide-react';
import { api, type Course, type User, type Student } from './api';
import './style.css';

type View = 'catalog' | 'mine' | 'profile';
type Modal = { type: 'auth'; register: boolean } | { type: 'course'; course: Course } | { type: 'edit'; course?: Course } | null;
const date = (value: string) => new Date(value).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long', year: 'numeric' });
const initials = (name: string) => name.split(' ').map(x => x[0]).slice(0, 2).join('').toUpperCase();
function App() {
  const [user, setUser] = useState<User | null>(null);
  const [ready, setReady] = useState(false);
  const [view, setView] = useState<View>('catalog');
  const [courses, setCourses] = useState<Course[]>([]);
  const [mine, setMine] = useState<Course[]>([]);
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState('new');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [modal, setModal] = useState<Modal>(null);
  const [revision, setRevision] = useState(0);
  const refresh = () => setRevision(n => n + 1);
  function logout() { sessionStorage.removeItem('studyflow-token'); setUser(null); setMine([]); setView('catalog'); setModal(null); }
  useEffect(() => {
    const expired = () => { logout(); setNotice('Сессия истекла. Войдите снова.'); };
    window.addEventListener('session-expired', expired);
    if (sessionStorage.getItem('studyflow-token')) api<User>('/me/').then(setUser).catch(e => setNotice(e.message)).finally(() => setReady(true));
    else setReady(true);
    return () => window.removeEventListener('session-expired', expired);
  }, []);
  useEffect(() => { if (notice) { const timer = setTimeout(() => setNotice(''), 5000); return () => clearTimeout(timer); } }, [notice]);
  useEffect(() => {
    if (!ready) return;
    const controller = new AbortController();
    setLoading(true); setError('');
    Promise.all([api<Course[]>('/courses/', {signal: controller.signal}), user ? api<Course[]>(user.role === 'teacher' ? '/courses/my' : '/me/courses', {signal: controller.signal}) : Promise.resolve([])])
      .then(([all, own]) => { setCourses(all); setMine(own); })
      .catch(e => { if (!controller.signal.aborted) setError(e.message); })
      .finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [user, revision, ready]);
  const visible = (view === 'mine' ? mine : courses).filter(c => c.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a, b) => sort === 'title' ? a.title.localeCompare(b.title) : b.created_at.localeCompare(a.created_at) || b.id - a.id);
  function navigate(next: View) { if (next !== 'catalog' && !user) { setModal({type: 'auth', register: false}); return; } setView(next); setQuery(''); }
  return <div className="app-shell">
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e => {e.preventDefault(); navigate('catalog');}}><span className="brand-icon"><BookOpen size={23}/></span>studyflow<span className="brand-dot">.</span></a>
      <div className="workspace-label">ВАШЕ ПРОСТРАНСТВО</div>
      <nav>{([{id:'catalog', label:'Каталог курсов', icon:LayoutGrid},{id:'mine', label:user?.role === 'teacher' ? 'Мои программы' : 'Моё обучение', icon:GraduationCap},{id:'profile', label:'Настройки профиля', icon:Settings}] as const).map(item => <button key={item.id} className={view === item.id ? 'nav-item active' : 'nav-item'} onClick={() => navigate(item.id)}><item.icon size={20}/>{item.label}{view === item.id && <span className="nav-dot"/>}</button>)}</nav>
      <div className="sidebar-note"><span className="little-star">✳</span><h3>Маленький шаг.<br/>Большие возможности.</h3><p>Новые знания начинаются с вашего любопытства.</p><button onClick={() => navigate('catalog')}>Найти свой курс <ArrowUpRight size={17}/></button></div>
      <div className="sidebar-bottom"><span className="status-dot"/> Пространство для роста <span>© 2026</span></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Пространство <ChevronRight size={14}/><strong>{view === 'catalog' ? 'Каталог' : view === 'mine' ? 'Мои курсы' : 'Профиль'}</strong></div>{user ? <div className="account"><span className="avatar">{initials(user.full_name)}</span><div><strong>{user.full_name}</strong><small>{user.role === 'teacher' ? 'Преподаватель' : 'Студент'}</small></div><button className="icon-button" aria-label="Выйти" onClick={logout}><LogOut size={19}/></button></div> : <button className="button small" disabled={!ready} onClick={() => setModal({type:'auth', register:false})}>Войти <ArrowUpRight size={16}/></button>}</header>
    <main>{view === 'profile' && user ? <Profile user={user} onUpdate={u => {setUser(u);setNotice('Профиль обновлён');}} onDelete={() => {logout();setNotice('Аккаунт удалён');}}/> : <>
      <div className="page-heading"><div><div className="eyebrow">УЧИТЕСЬ. ОТКРЫВАЙТЕ. РАСТИТЕ.</div><h1>{view === 'catalog' ? 'Знания, которые двигают вперёд' : user?.role === 'teacher' ? 'Делитесь тем, что знаете' : 'Ваш путь к новым знаниям'}</h1><p>{view === 'catalog' ? 'Найдите то, что вдохновляет. Сделайте следующий шаг уже сегодня.' : 'Все ваши курсы собраны в одном пространстве.'}</p></div>{user?.role === 'teacher' && <button className="button" onClick={() => setModal({type:'edit'})}><Plus size={18}/>Создать курс</button>}</div>
      <section className="hero"><div className="hero-copy"><span className="hero-tag"><Sparkles size={14}/> ВАШ СЛЕДУЮЩИЙ ШАГ</span><h2>Будущее начинается<br/>с «хочу разобраться».</h2><p>Учитесь у тех, кто любит своё дело.<br/>В своём ритме. С интересом. Для себя.</p><button className="button light" onClick={() => document.getElementById('course-list')?.scrollIntoView({behavior:'smooth'})}>Исследовать курсы <ArrowUpRight size={18}/></button></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="art-spark">✳</span><div className="book book-back"/><div className="book book-front"><span>OPEN YOUR<br/>NEXT CHAPTER.</span><BookOpen size={50}/><small>STUDYFLOW / KNOWLEDGE SERIES</small></div><span className="art-caption">БОЛЬШЕ, ЧЕМ ПРОСТО ЗНАНИЯ ↗</span></div></section>
      <div className="stats"><div><span className="stat-icon"><Library size={22}/></span><div><strong>{loading || error ? '—' : courses.length}</strong><span>курсов для открытий</span></div></div><div><span className="stat-icon peach"><Users size={22}/></span><div><strong>{loading || error ? '—' : new Set(courses.map(c => c.teacher.id)).size}</strong><span>преподавателей</span></div></div><div><span className="stat-icon violet"><GraduationCap size={23}/></span><div><strong>{user ? loading || error ? '—' : mine.length : 'Ваш темп'}</strong><span>{user ? user.role === 'teacher' ? 'созданных вами курсов' : 'в вашем обучении' : 'ваша траектория обучения'}</span></div></div></div>
      <section id="course-list"><div className="section-heading"><div><h2>{view === 'mine' ? 'Мои курсы' : 'Откройте для себя новое'} <span className="count">{loading ? '…' : visible.length}</span></h2><p>{view === 'mine' ? 'Продолжайте там, где вам интересно.' : 'Один курс может стать началом чего-то большего.'}</p></div><select aria-label="Сортировать курсы" value={sort} onChange={e => setSort(e.target.value)}><option value="new">Сначала новые</option><option value="title">По названию</option></select></div>
      <div className="catalog-toolbar"><div className="tabs"><button className={view === 'catalog' ? 'selected' : ''} onClick={() => navigate('catalog')}>Все курсы</button><button className={view === 'mine' ? 'selected' : ''} onClick={() => navigate('mine')}>Мои курсы</button></div><label className="search"><Search size={18}/><input placeholder="Найти интересный курс…" aria-label="Поиск по названию" value={query} onChange={e => setQuery(e.target.value)}/>{query && <button aria-label="Очистить поиск" onClick={() => setQuery('')}><X size={15}/></button>}</label></div>
      {error ? <div className="empty error-panel"><BookOpen/><h3>Не удалось загрузить курсы</h3><p>{error}</p><button className="button" onClick={refresh}>Попробовать снова</button></div> : loading ? <div className="course-grid" aria-label="Загрузка курсов">{[1,2,3].map(n => <div className="skeleton" key={n}/>)}</div> : visible.length ? <div className="course-grid">{visible.map(course => <button className="course-card" key={course.id} onClick={() => setModal({type:'course', course})}><div className={`course-cover cover-${course.id % 4}`}><span className="cover-label">STUDYFLOW CLASS</span><span className="cover-symbol">{['↗','✳','◈','⌘'][course.id % 4]}</span><span className="cover-number">{String(course.id).padStart(2,'0')}</span>{mine.some(c => c.id === course.id) && <span className="enrolled-badge"><Check size={12}/> Мой курс</span>}</div><div className="course-body"><span className="course-kicker">ОБУЧЕНИЕ БЕЗ ГРАНИЦ</span><h3>{course.title}</h3><p>{course.description}</p><div className="teacher"><span className="mini-avatar">{initials(course.teacher.full_name)}</span><span>{course.teacher.full_name}</span><ArrowUpRight size={19}/></div></div></button>)}</div> : <div className="empty"><BookOpen size={34}/><h3>{query ? 'Пока ничего не нашлось' : view === 'mine' ? 'Здесь начнётся ваш путь' : 'Пространство ждёт первые курсы'}</h3><p>{query ? 'Попробуйте другое название или очистите поиск.' : view === 'mine' ? 'Выберите курс в каталоге или создайте свою программу.' : 'Преподаватели могут добавить первый курс в своём кабинете.'}</p><button className="button" onClick={() => {if(query) setQuery(''); else if(user?.role === 'teacher') setModal({type:'edit'}); else if(view === 'mine') navigate('catalog'); else setModal({type:'auth', register:true});}}>{query ? 'Сбросить поиск' : user?.role === 'teacher' ? 'Создать курс' : view === 'mine' ? 'Открыть каталог' : 'Присоединиться'}<ArrowRight size={17}/></button></div>}</section>
    </>}<footer><span>studyflow<span className="brand-dot">.</span></span><p>Любопытство — хорошее начало.</p><span>Сделайте шаг к новому ↗</span></footer></main></div>
    {notice && <div className="toast" role="status"><Check size={18}/>{notice}<button aria-label="Закрыть уведомление" onClick={() => setNotice('')}><X size={16}/></button></div>}
    {modal && <Dialog onClose={() => setModal(null)}>{modal.type === 'auth' ? <Auth register={modal.register} switchMode={() => setModal({type:'auth',register:!modal.register})} onLogin={u => {setUser(u);setModal(null);setNotice('Добро пожаловать в StudyFlow!');}}/> : modal.type === 'edit' ? <CourseEditor course={modal.course} onSave={() => {setModal(null); refresh();setNotice('Курс сохранён');}}/> : <CourseDetails course={modal.course} user={user} enrolled={mine.some(c => c.id === modal.course.id)} onAuth={() => setModal({type:'auth',register:false})} onEdit={() => setModal({type:'edit',course:modal.course})} onChange={message => {refresh();setNotice(message);setModal(null);}}/>}</Dialog>}
  </div>;
}
function Dialog({children,onClose}: {children:React.ReactNode;onClose:()=>void}) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => {const dialog = ref.current!; dialog.showModal(); const old = document.body.style.overflow; document.body.style.overflow='hidden'; return () => {document.body.style.overflow=old;};}, []);
  return <dialog ref={ref} onCancel={onClose} aria-label="StudyFlow" onClick={e => {if(e.target === ref.current) onClose();}}><button className="dialog-close icon-button" aria-label="Закрыть" onClick={onClose}><X size={21}/></button>{children}</dialog>;
}
function FormError({error}:{error:string}) {return error ? <p className="form-error" role="alert">{error}</p> : null;}
function Submit({busy,children}:{busy:boolean;children:React.ReactNode}) {return <button className="button" type="submit" disabled={busy}>{busy ? <LoaderCircle className="spin" size={18}/> : children}</button>;}
function Auth({register,switchMode,onLogin}:{register:boolean;switchMode:()=>void;onLogin:(u:User)=>void}) {
  const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); setBusy(true);setError(''); let registered = false;
    try {if(register) {await api('/auth/register',{method:'POST',body:JSON.stringify(Object.fromEntries(data))}); registered = true;}
      const token = await api<{access_token:string}>('/auth/login',{method:'POST',body:new URLSearchParams({username:String(data.get('username')),password:String(data.get('password'))})});
      sessionStorage.setItem('studyflow-token',token.access_token); const u = await api<User>('/me/'); onLogin(u);
    } catch(e) {setError((registered ? 'Аккаунт создан. Перейдите ко входу. ' : '') + (e as Error).message);} finally {setBusy(false);}
  }
  return <><div className="modal-symbol"><GraduationCap/></div><div className="eyebrow">ВАШЕ ПРОСТРАНСТВО ЗНАНИЙ</div><h2>{register ? 'Начнём что-то новое' : 'Рады видеть вас снова'}</h2><p className="muted">{register ? 'Создайте аккаунт и выберите свой путь.' : 'Войдите, чтобы продолжить свой путь.'}</p><form onSubmit={submit}>{register && <label>Полное имя<input name="full_name" required maxLength={120} autoComplete="name"/></label>}<label>Имя пользователя<input name="username" required maxLength={80} autoComplete="username"/></label><label>Пароль<input name="password" type="password" required autoComplete={register ? 'new-password':'current-password'}/></label>{register && <label>Я хочу<select name="role"><option value="student">Учиться — студент</option><option value="teacher">Преподавать — преподаватель</option></select></label>}<FormError error={error}/><Submit busy={busy}>{register ? 'Создать аккаунт' : 'Войти'}<ArrowRight size={17}/></Submit></form><button className="text-button" disabled={busy} onClick={() => {setError('');switchMode();}}>{register ? 'Уже есть аккаунт? Войти' : 'Впервые здесь? Создать аккаунт'}</button></>;
}
function CourseEditor({course,onSave}:{course?:Course;onSave:()=>void}) {
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{await api(course ? `/courses/${course.id}`:'/courses/',{method:course?'PATCH':'POST',body:JSON.stringify(Object.fromEntries(data))});onSave();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><div className="eyebrow">КАБИНЕТ ПРЕПОДАВАТЕЛЯ</div><h2>{course?'Редактировать курс':'Новый курс'}</h2><p className="muted">Помогите студентам найти своё следующее открытие.</p><form onSubmit={submit}><label>Название курса<input name="title" required maxLength={200} defaultValue={course?.title} placeholder="Например, основы Python"/></label><label>Описание<textarea name="description" rows={7} required defaultValue={course?.description} placeholder="Чему вы научите и кому подойдёт этот курс?"/></label><FormError error={error}/><Submit busy={busy}>Сохранить курс<Check size={18}/></Submit></form></>;
}
function CourseDetails({course,user,enrolled,onAuth,onEdit,onChange}:{course:Course;user:User|null;enrolled:boolean;onAuth:()=>void;onEdit:()=>void;onChange:(s:string)=>void}) {
  const [students,setStudents]=useState<Student[]>([]);const [error,setError]=useState('');const [studentsError,setStudentsError]=useState('');const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);const [confirm,setConfirm]=useState(false);
  useEffect(()=>{const controller=new AbortController();api<Student[]>(`/courses/${course.id}/students`,{signal:controller.signal}).then(setStudents).catch(e=>{if(!controller.signal.aborted)setStudentsError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoaded(true);});return()=>controller.abort();},[course.id]);
  const owner = user?.id === course.teacher.id;
  async function action(remove=false){setBusy(true);setError('');try{await api(remove?`/courses/${course.id}`:enrolled?`/me/courses/${course.id}`:'/me/courses/',{method:remove||enrolled?'DELETE':'POST',...(!remove&&!enrolled?{body:JSON.stringify({course_id:course.id})}:{})});onChange(remove?'Курс удалён':enrolled?'Вы покинули курс':'Вы записаны на курс!');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><div className={`detail-cover course-cover cover-${course.id%4}`}><span className="cover-symbol">{['↗','✳','◈','⌘'][course.id%4]}</span></div><div className="eyebrow">STUDYFLOW CLASS</div><h2>{course.title}</h2><div className="detail-meta"><span>{course.teacher.full_name}</span><span>{date(course.created_at)}</span></div><p className="description">{course.description}</p><div className="students"><h3>Участники {loaded&&!studentsError&&`· ${students.length}`}</h3>{studentsError?<p role="alert">{studentsError}</p>:!loaded?<p>Загрузка…</p>:students.length?students.map(s=><div className="student" key={s.id}><span className="mini-avatar">{initials(s.full_name)}</span>{s.full_name}<small>@{s.username}</small></div>):<p className="muted">На этот курс пока никто не записался.</p>}</div><FormError error={error}/><div className="actions">{owner?<><button className="button" onClick={onEdit} disabled={busy}>Редактировать</button><button className="button danger" disabled={busy} onClick={()=>setConfirm(true)}>Удалить курс</button></>:!user?<button className="button" onClick={onAuth}>Войти и записаться<ArrowRight size={17}/></button>:user.role==='student'?<button className="button" disabled={busy} onClick={()=>enrolled?setConfirm(true):action()}>{busy?'Сохраняем…':enrolled?'Покинуть курс':'Записаться на курс'}</button>:<p className="muted">Запись на курсы доступна студентам.</p>}</div>{confirm&&<div className="confirm"><p>{owner?'Удалить курс и связанные записи студентов?':'Покинуть этот курс?'}</p><button className="button danger" disabled={busy} onClick={()=>action(owner)}>Да, {owner?'удалить':'покинуть'}</button><button className="text-button" disabled={busy} onClick={()=>setConfirm(false)}>Отмена</button></div>}</>;
}
function Profile({user,onUpdate,onDelete}:{user:User;onUpdate:(u:User)=>void;onDelete:()=>void}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [confirm,setConfirm]=useState(false);
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{onUpdate(await api<User>('/me/',{method:'PATCH',body:JSON.stringify(Object.fromEntries(data))}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function remove(){setBusy(true);setError('');try{await api('/me/',{method:'DELETE'});onDelete();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><div className="eyebrow">ЛИЧНОЕ ПРОСТРАНСТВО</div><h1>Настройки профиля</h1><p className="muted">Пусть ваше пространство будет вашим.</p><section className="profile-panel"><div className="profile-summary"><span className="avatar large">{initials(user.full_name)}</span><div><h2>{user.full_name}</h2><p>{user.role==='teacher'?'Преподаватель':'Студент'} · С нами с {date(user.created_at)}</p></div></div><form onSubmit={save}><label>Полное имя<input name="full_name" required maxLength={120} defaultValue={user.full_name}/></label><label>Имя пользователя<input name="username" required maxLength={80} defaultValue={user.username}/></label><FormError error={error}/><Submit busy={busy}>Сохранить изменения</Submit></form><div className="danger-zone"><h3>Удаление аккаунта</h3><p>Аккаунт будет удалён без возможности восстановления.</p>{confirm?<><p>Вы уверены, что хотите удалить аккаунт?</p><button className="button danger" disabled={busy} onClick={remove}>Удалить навсегда</button><button className="text-button" disabled={busy} onClick={()=>setConfirm(false)}>Отмена</button></>:<button className="button danger" onClick={()=>setConfirm(true)}>Удалить аккаунт</button>}</div></section></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
